<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_concat(CHEF, , S CAKE WORLD)_fa fa-question fa-stack-1x enquirepopup</name>
   <tag></tag>
   <elementGuidId>95bba2d3-3a7a-4e09-a58d-abef5631d400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outputsort']/div[3]/div/div[2]/div/span[2]/i[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa-stack.fa-lg.enquirepopup.enquirycirclepromos > i.fa.fa-question.fa-stack-1x.enquirepopup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-question fa-stack-1x enquirepopup</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promodetails</name>
      <type>Main</type>
      <value>Lock-down worrying your anniversary or birthday bash.?!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bname</name>
      <type>Main</type>
      <value>CHEF'S CAKE WORLD</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-businesslocationid</name>
      <type>Main</type>
      <value>426</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promotionid</name>
      <type>Main</type>
      <value>2205</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outputsort&quot;)/div[@class=&quot;isotope-holder col-md-4 col-sm-6 col-xs-12 marB20 12 cate4&quot;]/div[@class=&quot;element-itmes-wrapper&quot;]/div[@class=&quot;box-detail deals-sidebar&quot;]/div[@class=&quot;robocart&quot;]/span[@class=&quot;fa-stack fa-lg enquirepopup enquirycirclepromos&quot;]/i[@class=&quot;fa fa-question fa-stack-1x enquirepopup&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outputsort']/div[3]/div/div[2]/div/span[2]/i[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]/i[2]</value>
   </webElementXpaths>
</WebElementEntity>
