<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>question fa-stack-1x enquirepopup</name>
   <tag></tag>
   <elementGuidId>6dbfe0b6-b733-42d4-9817-fa16e1f05cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//figcaption[@id='robocart_1865']/span[2]/i[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#robocart_1865 > span.fa-stack.fa-lg.enquirepopup > i.fa.fa-question.fa-stack-1x.enquirepopup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-question fa-stack-1x enquirepopup</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promodetails</name>
      <type>Main</type>
      <value>Buy One Greenchef Glasstop Namo 3 Burner Gas Stove and Get Rs.1000/- Off. Order through Hoppon and get it delivered at your place!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bname</name>
      <type>Main</type>
      <value>Kunnil Hyper Market, Kaniyapuram</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-businesslocationid</name>
      <type>Main</type>
      <value>412</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promotionid</name>
      <type>Main</type>
      <value>1865</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider&quot;)/div[@class=&quot;owl-stage-outer&quot;]/div[@class=&quot;owl-stage&quot;]/div[@class=&quot;owl-item active center&quot;]/div[@id=&quot;test1&quot;]/div[@class=&quot;img-prmo-div borderimg nocaption&quot;]/figure[@id=&quot;featrdpromo_click&quot;]/figcaption[@id=&quot;robocart_1865&quot;]/span[@class=&quot;fa-stack fa-lg enquirepopup&quot;]/i[@class=&quot;fa fa-question fa-stack-1x enquirepopup&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figcaption[@id='robocart_1865']/span[2]/i[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/figure/figcaption/span[2]/i[2]</value>
   </webElementXpaths>
</WebElementEntity>
