<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-dropdown_shoplist</name>
   <tag></tag>
   <elementGuidId>033e88b5-9301-402f-8e17-afb4220f9afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='promosfilterstore']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#promosfilterstore</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>promosfilterstore</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promosfilterstore</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- All --AARIYAS Vegetarian RestaurantAgnikoneAjwa RestaurantAlappey House RestaurantAlif Mandi HouseAll Day Bakes And CafeAmset AmbienceAnnapoorna KitchenA-One FurnitureAPS Vegetables &amp; Provision StoreArabeiq ParadiseArabesque Fried and Grill Chicken RestaurantArabian Tasty CafeAsian BakersAutowizeAzlina's Fashion BoutiqueBait Al Mandi RestaurantBarakatBaskin Robbins - TechnomallBig basketBikash Babu Sweets, KowdiarBikash Babu Sweets, KulathoorBiriyani DarbarBIRIYANI PARADISEBuraq RestaurantCafe M2, Phase 1CAFFE PRIMOCATE FACTORYChalai Stores, VattiyoorkavuCHEF'S CAKE WORLDChengayeesCloud 9 CakesCoffee ParkConcept Tyres  Pete'sCorden BleuCore Convenient StoreDakshinDakshinDanbaukDanbauk TechnoparkDhe KozhikodanDining TableDivine ShopEssar Bakes &amp; RestaurantFlavouritesFood  BazarFrankztreat CafeFruit N IceFun StickGaram MasalaGODAVARIGod's Own SpicesGolden ThreadGreen BasketGreen Habito, KazhakkoottamGreen Habito, PalayamGreen Trends SreekaryamGreens SupermarketHaji AliHotel AryaasHotel VivinI WON'T DIETIcy CuppaIndroyal Home SpacesJode's Cake WorldKARUMURA SNACKSKOC ChickenKOC VegetablesKOOTTUKARUDE KADAKOTTAYAM KITCHENKraft WeaversKunnil Health &amp; HygieneKunnil Health and HygieneKunnil Hyper Market, KaniyapuramKunnil Hypermarket KulathoorKunnil Hypermarket Kulathoor, Gift CardKunnil Hypermarket, Kuravankonam.Kunnil Margin Free Market, MCKunnil Margin Free, ParuthipparaKunnil Supermarket, VattiyoorkavuLa Bella Vita by TamaraLa' Delicious Bakery and CafeLakshmi Margin Free SupermarketLalu's ChipsLe'CafeLilac Fusion RestaurantM BAKE &amp; JUICESM SquaredMad'oak LifestyleMaga Furnishing HouseMaggi PointMaha BoliMaha ChipsMaha Chips, VellayambalamMaitry SupermarketMargin Free Supermarket, KumarapuramMax, MG RoadMayfairNeel's Ambur BiriyaniNest Super Market, KillipalamNilgiris Supermarket MG RoadNilgiris Supermarket SreekaryamO by TAMARAOld's Cool BistroOru IlapothiPADHEYAM FOOD COURTPitlane ExpresswashPondis Pizza HubPreethy Health and HygienePreethy SupermarketPunartham StoresQRS M G RoadQRS MG Road, Gift CardQRS Sreekaryam, Gift CardQRS Super Centre, SreekaryamQuality Supermarket, KZKTMRangoli RestaurantRetouche Home AppliancesRoopa Beauty Clinic &amp; SpaRoyal CafeSaadia Margin Free SupermarketSijis Pizza StreetSlice of Spice KazhakoottamSonu's Magic KitchenSony Center, PattomSpecialOrder shopStar Chef Bake and Make RestaurantStove CentreStyle PlusSUGUNA DAILY FRESH SREEKARYAMSwad: Flavours &amp; PlattersSweet Mahal, Bakery Jn.TERRACEThakkaaram KazhakkoottamTHAMPI'S TAKE AWAY KZKTMTHAMPI'S TAKE AWAY, KARAMANAThayillam PaintsTHE AUTHENTIC MALABARI DUM BIRIYANIThe Helmet World - NanthancodeThe Helmet World KazhakoottamThe Passion FruitTravancore Arabian GrillTRIVANDRUM CHICKEN CORNERTrivandrum Chicken Corner, KazhakuttomUNIQUEZ AUTO HUBUP NORTH RESTAURANTVayaloram Family RestaurantVembanad RestaurantWorld of Titan, Pattom</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promosfilterstore&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='promosfilterstore']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='next'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='prev'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Nearest Shops'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Expiry Date'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'promosfilterstore' and @id = 'promosfilterstore' and (text() = concat(&quot;-- All --AARIYAS Vegetarian RestaurantAgnikoneAjwa RestaurantAlappey House RestaurantAlif Mandi HouseAll Day Bakes And CafeAmset AmbienceAnnapoorna KitchenA-One FurnitureAPS Vegetables &amp; Provision StoreArabeiq ParadiseArabesque Fried and Grill Chicken RestaurantArabian Tasty CafeAsian BakersAutowizeAzlina&quot; , &quot;'&quot; , &quot;s Fashion BoutiqueBait Al Mandi RestaurantBarakatBaskin Robbins - TechnomallBig basketBikash Babu Sweets, KowdiarBikash Babu Sweets, KulathoorBiriyani DarbarBIRIYANI PARADISEBuraq RestaurantCafe M2, Phase 1CAFFE PRIMOCATE FACTORYChalai Stores, VattiyoorkavuCHEF&quot; , &quot;'&quot; , &quot;S CAKE WORLDChengayeesCloud 9 CakesCoffee ParkConcept Tyres  Pete&quot; , &quot;'&quot; , &quot;sCorden BleuCore Convenient StoreDakshinDakshinDanbaukDanbauk TechnoparkDhe KozhikodanDining TableDivine ShopEssar Bakes &amp; RestaurantFlavouritesFood  BazarFrankztreat CafeFruit N IceFun StickGaram MasalaGODAVARIGod&quot; , &quot;'&quot; , &quot;s Own SpicesGolden ThreadGreen BasketGreen Habito, KazhakkoottamGreen Habito, PalayamGreen Trends SreekaryamGreens SupermarketHaji AliHotel AryaasHotel VivinI WON&quot; , &quot;'&quot; , &quot;T DIETIcy CuppaIndroyal Home SpacesJode&quot; , &quot;'&quot; , &quot;s Cake WorldKARUMURA SNACKSKOC ChickenKOC VegetablesKOOTTUKARUDE KADAKOTTAYAM KITCHENKraft WeaversKunnil Health &amp; HygieneKunnil Health and HygieneKunnil Hyper Market, KaniyapuramKunnil Hypermarket KulathoorKunnil Hypermarket Kulathoor, Gift CardKunnil Hypermarket, Kuravankonam.Kunnil Margin Free Market, MCKunnil Margin Free, ParuthipparaKunnil Supermarket, VattiyoorkavuLa Bella Vita by TamaraLa&quot; , &quot;'&quot; , &quot; Delicious Bakery and CafeLakshmi Margin Free SupermarketLalu&quot; , &quot;'&quot; , &quot;s ChipsLe&quot; , &quot;'&quot; , &quot;CafeLilac Fusion RestaurantM BAKE &amp; JUICESM SquaredMad&quot; , &quot;'&quot; , &quot;oak LifestyleMaga Furnishing HouseMaggi PointMaha BoliMaha ChipsMaha Chips, VellayambalamMaitry SupermarketMargin Free Supermarket, KumarapuramMax, MG RoadMayfairNeel&quot; , &quot;'&quot; , &quot;s Ambur BiriyaniNest Super Market, KillipalamNilgiris Supermarket MG RoadNilgiris Supermarket SreekaryamO by TAMARAOld&quot; , &quot;'&quot; , &quot;s Cool BistroOru IlapothiPADHEYAM FOOD COURTPitlane ExpresswashPondis Pizza HubPreethy Health and HygienePreethy SupermarketPunartham StoresQRS M G RoadQRS MG Road, Gift CardQRS Sreekaryam, Gift CardQRS Super Centre, SreekaryamQuality Supermarket, KZKTMRangoli RestaurantRetouche Home AppliancesRoopa Beauty Clinic &amp; SpaRoyal CafeSaadia Margin Free SupermarketSijis Pizza StreetSlice of Spice KazhakoottamSonu&quot; , &quot;'&quot; , &quot;s Magic KitchenSony Center, PattomSpecialOrder shopStar Chef Bake and Make RestaurantStove CentreStyle PlusSUGUNA DAILY FRESH SREEKARYAMSwad: Flavours &amp; PlattersSweet Mahal, Bakery Jn.TERRACEThakkaaram KazhakkoottamTHAMPI&quot; , &quot;'&quot; , &quot;S TAKE AWAY KZKTMTHAMPI&quot; , &quot;'&quot; , &quot;S TAKE AWAY, KARAMANAThayillam PaintsTHE AUTHENTIC MALABARI DUM BIRIYANIThe Helmet World - NanthancodeThe Helmet World KazhakoottamThe Passion FruitTravancore Arabian GrillTRIVANDRUM CHICKEN CORNERTrivandrum Chicken Corner, KazhakuttomUNIQUEZ AUTO HUBUP NORTH RESTAURANTVayaloram Family RestaurantVembanad RestaurantWorld of Titan, Pattom&quot;) or . = concat(&quot;-- All --AARIYAS Vegetarian RestaurantAgnikoneAjwa RestaurantAlappey House RestaurantAlif Mandi HouseAll Day Bakes And CafeAmset AmbienceAnnapoorna KitchenA-One FurnitureAPS Vegetables &amp; Provision StoreArabeiq ParadiseArabesque Fried and Grill Chicken RestaurantArabian Tasty CafeAsian BakersAutowizeAzlina&quot; , &quot;'&quot; , &quot;s Fashion BoutiqueBait Al Mandi RestaurantBarakatBaskin Robbins - TechnomallBig basketBikash Babu Sweets, KowdiarBikash Babu Sweets, KulathoorBiriyani DarbarBIRIYANI PARADISEBuraq RestaurantCafe M2, Phase 1CAFFE PRIMOCATE FACTORYChalai Stores, VattiyoorkavuCHEF&quot; , &quot;'&quot; , &quot;S CAKE WORLDChengayeesCloud 9 CakesCoffee ParkConcept Tyres  Pete&quot; , &quot;'&quot; , &quot;sCorden BleuCore Convenient StoreDakshinDakshinDanbaukDanbauk TechnoparkDhe KozhikodanDining TableDivine ShopEssar Bakes &amp; RestaurantFlavouritesFood  BazarFrankztreat CafeFruit N IceFun StickGaram MasalaGODAVARIGod&quot; , &quot;'&quot; , &quot;s Own SpicesGolden ThreadGreen BasketGreen Habito, KazhakkoottamGreen Habito, PalayamGreen Trends SreekaryamGreens SupermarketHaji AliHotel AryaasHotel VivinI WON&quot; , &quot;'&quot; , &quot;T DIETIcy CuppaIndroyal Home SpacesJode&quot; , &quot;'&quot; , &quot;s Cake WorldKARUMURA SNACKSKOC ChickenKOC VegetablesKOOTTUKARUDE KADAKOTTAYAM KITCHENKraft WeaversKunnil Health &amp; HygieneKunnil Health and HygieneKunnil Hyper Market, KaniyapuramKunnil Hypermarket KulathoorKunnil Hypermarket Kulathoor, Gift CardKunnil Hypermarket, Kuravankonam.Kunnil Margin Free Market, MCKunnil Margin Free, ParuthipparaKunnil Supermarket, VattiyoorkavuLa Bella Vita by TamaraLa&quot; , &quot;'&quot; , &quot; Delicious Bakery and CafeLakshmi Margin Free SupermarketLalu&quot; , &quot;'&quot; , &quot;s ChipsLe&quot; , &quot;'&quot; , &quot;CafeLilac Fusion RestaurantM BAKE &amp; JUICESM SquaredMad&quot; , &quot;'&quot; , &quot;oak LifestyleMaga Furnishing HouseMaggi PointMaha BoliMaha ChipsMaha Chips, VellayambalamMaitry SupermarketMargin Free Supermarket, KumarapuramMax, MG RoadMayfairNeel&quot; , &quot;'&quot; , &quot;s Ambur BiriyaniNest Super Market, KillipalamNilgiris Supermarket MG RoadNilgiris Supermarket SreekaryamO by TAMARAOld&quot; , &quot;'&quot; , &quot;s Cool BistroOru IlapothiPADHEYAM FOOD COURTPitlane ExpresswashPondis Pizza HubPreethy Health and HygienePreethy SupermarketPunartham StoresQRS M G RoadQRS MG Road, Gift CardQRS Sreekaryam, Gift CardQRS Super Centre, SreekaryamQuality Supermarket, KZKTMRangoli RestaurantRetouche Home AppliancesRoopa Beauty Clinic &amp; SpaRoyal CafeSaadia Margin Free SupermarketSijis Pizza StreetSlice of Spice KazhakoottamSonu&quot; , &quot;'&quot; , &quot;s Magic KitchenSony Center, PattomSpecialOrder shopStar Chef Bake and Make RestaurantStove CentreStyle PlusSUGUNA DAILY FRESH SREEKARYAMSwad: Flavours &amp; PlattersSweet Mahal, Bakery Jn.TERRACEThakkaaram KazhakkoottamTHAMPI&quot; , &quot;'&quot; , &quot;S TAKE AWAY KZKTMTHAMPI&quot; , &quot;'&quot; , &quot;S TAKE AWAY, KARAMANAThayillam PaintsTHE AUTHENTIC MALABARI DUM BIRIYANIThe Helmet World - NanthancodeThe Helmet World KazhakoottamThe Passion FruitTravancore Arabian GrillTRIVANDRUM CHICKEN CORNERTrivandrum Chicken Corner, KazhakuttomUNIQUEZ AUTO HUBUP NORTH RESTAURANTVayaloram Family RestaurantVembanad RestaurantWorld of Titan, Pattom&quot;))]</value>
   </webElementXpaths>
</WebElementEntity>
