<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delivery</name>
   <tag></tag>
   <elementGuidId>f2f3fe5d-f0c2-4cf9-be89-4303e52ee453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deliverypickupcheck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='deliverypickupcheck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99f26efa-01ab-44e5-b4c6-1a76a2fefa7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fa7d8445-0d5d-4a6e-a71e-ed9972582d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deliverycheckradio</value>
      <webElementGuid>10031569-66a8-44e0-816d-03bd5801f288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deliverypickupcheck</value>
      <webElementGuid>d6efb30c-302e-48b3-855f-b914ba1c9b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>deliverypickupcheck();</value>
      <webElementGuid>97b39c39-c1f0-41a5-8848-96415778dd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deliverydineincheckoption</value>
      <webElementGuid>95634f8a-2c4c-4469-b86c-bea67066b3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9ba0e154-b67e-44a4-9cb5-cb96c3cde6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deliverypickupcheck&quot;)</value>
      <webElementGuid>95c73b13-2bb1-4a78-966e-ef387dd67912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db243668-8ccb-4edb-8e96-2e1a02101d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a451595c-c725-4005-a156-e44f60f95b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deliverycheckradio</value>
      <webElementGuid>6bd22693-645f-43c8-ad78-ebfd58dde0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deliverypickupcheck</value>
      <webElementGuid>e30cf7de-4958-4b07-b54f-9838339d2f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>deliverypickupcheck();</value>
      <webElementGuid>d0475bc6-2ca1-4c9f-b6dd-bd8350d7a485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deliverydineincheckoption</value>
      <webElementGuid>1a81571a-0526-425c-ab78-9aca08b9e6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d558b6a9-ba9b-4e32-a0cd-f47d65ac0890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deliverypickupcheck&quot;)</value>
      <webElementGuid>c642663d-01e7-4825-a103-fabc0770b6ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='deliverypickupcheck']</value>
      <webElementGuid>ec49dd2d-1ac5-4df6-b800-561604a73f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dineinoptionavailpopup']/div/div/div[2]/input[6]</value>
      <webElementGuid>5d766137-4144-408e-a8bc-d9b4fdf1dfe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[6]</value>
      <webElementGuid>5a65e4e3-5205-4de3-b784-cb5d8756bb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'deliverypickupcheck' and @name = 'deliverydineincheckoption']</value>
      <webElementGuid>b7b31f22-85c3-4f75-96d7-2cf0afca3773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
