<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dine_in</name>
   <tag></tag>
   <elementGuidId>fe0c3df7-668b-4af3-9bfc-af565bf29c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dineincheckoption</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dineincheckoption']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d1ddd1d-78af-48fb-8281-ba0657f721fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>32cd51b3-ffac-4f4e-9566-392e14bc8a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deliverycheckradio</value>
      <webElementGuid>f58a44a6-6b87-4513-912a-ff57a95203c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dineincheckoption</value>
      <webElementGuid>ff182df4-ceb6-4a7d-969b-ca960b7480ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dineincheckoption(this);</value>
      <webElementGuid>9fcf2f11-ee45-4bb2-a1da-1e9a17e88245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isfromdineinpopup</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>89141c23-bcd3-4cf9-b3bd-62f14919fc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isglavail</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>273d303d-953c-4bee-989c-86518e5227d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vendorid</name>
      <type>Main</type>
      <value>307</value>
      <webElementGuid>bbee6e66-ec8d-4754-a1fe-b91bc42ec281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vendorname</name>
      <type>Main</type>
      <value>Arabian Tasty Cafe</value>
      <webElementGuid>1712f55c-afb5-4bf5-818b-f205cdae281d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>214222</value>
      <webElementGuid>db7002ba-3c70-4233-8cd1-0f195a946424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qty</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>35563c22-76ff-4e77-a1ad-2be6bc7610b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deliverydineincheckoption</value>
      <webElementGuid>96623c28-fc62-4221-b031-86365a118858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f05ca215-0d0c-4c48-b943-28d9aad13082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dineincheckoption&quot;)</value>
      <webElementGuid>68b40cc5-b7de-4b7c-a39b-4702b5bcecff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>260a0dd8-a986-40be-a5fa-ec3bacef05c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5e53679f-d323-4a11-afc8-c9425a89cb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deliverycheckradio</value>
      <webElementGuid>3c756039-f46d-46e7-be9a-0937e69f5071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dineincheckoption</value>
      <webElementGuid>9aa52e7c-f30f-4c92-a1b4-85a363ed34d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dineincheckoption(this);</value>
      <webElementGuid>99b640c4-6219-4c2e-83c1-31ecdb00abc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isfromdineinpopup</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>271efdd5-19ff-4102-ad77-0f3178bca562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isglavail</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c12c48ea-7b72-4ef5-9edc-75a606d9a291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vendorid</name>
      <type>Main</type>
      <value>307</value>
      <webElementGuid>fc929fae-c5b8-48f9-b2d0-f1b9c66bb760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vendorname</name>
      <type>Main</type>
      <value>Arabian Tasty Cafe</value>
      <webElementGuid>9591860f-bfa5-46e3-b9a0-1d509299165c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>214222</value>
      <webElementGuid>85b37b58-a497-4b3f-ba16-065497fc3c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qty</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b4445a83-3d5f-4025-b949-448461769e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deliverydineincheckoption</value>
      <webElementGuid>d2fc0449-88cc-418a-96e5-f858c796fa91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ee879358-4c31-4edc-abb0-cc18843424b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dineincheckoption&quot;)</value>
      <webElementGuid>1cd7f18f-1066-4076-be77-624d1585c455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dineincheckoption']</value>
      <webElementGuid>2ed466fe-5476-41d2-8dbf-4a8e9922ec0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dineinoptionavailpopup']/div/div/div[2]/input[5]</value>
      <webElementGuid>546db594-3e01-4b54-bda3-cf71e4cb0123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[5]</value>
      <webElementGuid>86c07f75-17a2-4085-af03-fa69c664ebe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dineincheckoption' and @name = 'deliverydineincheckoption']</value>
      <webElementGuid>c8a8dec7-fc3b-45ad-bd3b-8ab8cc56e5e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
