<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c7e5fdd0-4cbf-4202-a86e-f07965e8fba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outputsort']/div[14]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>269864a7-53db-458e-8802-74bcdd764657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hoppons3.s3.amazonaws.com/HoppOnImages/VendorLogo/BaskinRobbins-Technomall_20180103162008751_328e373b71434721a207d062ca7b4088.jpg</value>
      <webElementGuid>b0376a4d-abe8-4508-a38a-816ace0318f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>store</value>
      <webElementGuid>68446c76-35a3-489a-90b5-04fb39a64be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>ea9c9cfc-39d8-4428-b461-bcc7f13291f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>86c6551b-d719-45e6-b621-7856ec0b0bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>72ff6aa7-7660-4b58-b7d1-2fd2e62c04bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-shopid</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>de2fe161-8fc0-45dd-8eae-caa0d12d6cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outputsort&quot;)/div[@class=&quot;infopromoresetcat element-items gtaglink 12&quot;]/div[@class=&quot;element-itmes-wrapper&quot;]/a[1]/img[1]</value>
      <webElementGuid>ea0d09ad-5732-458f-8725-01dbf2134d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outputsort']/div[14]/div/a/img</value>
      <webElementGuid>cdf7e4ff-ef28-4d9a-961a-d59f94847068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='store'])[14]</value>
      <webElementGuid>d83fe8e6-f81c-4341-8eaf-14f09fc76be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/a/img</value>
      <webElementGuid>4ebd982d-f4a7-43d6-a37b-1d6ab1ecb99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hoppons3.s3.amazonaws.com/HoppOnImages/VendorLogo/BaskinRobbins-Technomall_20180103162008751_328e373b71434721a207d062ca7b4088.jpg' and @alt = 'store']</value>
      <webElementGuid>b7732ff4-dd79-4d7c-bf9b-ddbeecb44476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
