<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cones                                                                                    3</name>
   <tag></tag>
   <elementGuidId>23d47db1-6c2b-45fd-b417-62dd7b66e1f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show_more_211</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='show_more_211']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3c75e6e-e3ff-4a06-9d6f-d334d2e072f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>211</value>
      <webElementGuid>d72099cb-637c-476a-a828-a09c966fa115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_more_211</value>
      <webElementGuid>d21026d8-690e-4f0f-b371-e5af95187f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_next_content(211)</value>
      <webElementGuid>505e158d-d136-4bf6-b770-8897984c8132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>bde1df98-4169-4a10-8372-40a44d008358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-start</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>02b9352a-6965-454a-add9-268e6a2843b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagesize</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6d0a2212-4602-41f3-8d63-fc69df7c7948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prdcount</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ac969068-8aa7-4c1d-9fef-7daa0d85298a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>211</value>
      <webElementGuid>97ab117a-43da-40bf-bef7-4dec078d69fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-business</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>8b0973d7-d98a-4030-9f3f-c22042dfe2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productcategoryname</name>
      <type>Main</type>
      <value>Cones</value>
      <webElementGuid>c0433acf-7270-495b-9739-8e0f241939a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-businesslocationname</name>
      <type>Main</type>
      <value>Baskin Robbins - Technomall</value>
      <webElementGuid>4b7cb72b-e0e7-4e1e-b459-ca4979b361f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isorderavailableshop</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6652c663-750c-4e7f-8d54-636b73685141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ispickupavil</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5970983-afaa-4f50-ac8b-31ff3b8468ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isdeliveryavil</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ae83ccae-d225-4115-8e40-573f3e804585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isdineinavil</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a5325687-e48c-4805-bbe0-1be511466c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Cones
                                        
                                            3</value>
      <webElementGuid>84bc292b-72c0-4feb-88be-dd67754320fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_more_211&quot;)</value>
      <webElementGuid>b681bfcb-5adc-450a-b04c-838b3bcf081a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='show_more_211']</value>
      <webElementGuid>dbff4ab1-c860-4f0c-9357-37698dc5a592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='211']/a</value>
      <webElementGuid>944934e5-9c2f-4b87-96de-49b01469620d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cold Toppings (favourite)'])[1]/following::a[1]</value>
      <webElementGuid>0772bf67-3f59-480f-ae90-6c83998ac677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cold Toppings (divine)'])[1]/following::a[2]</value>
      <webElementGuid>b45f5f1a-93c7-46e4-89c2-5bc235ef9755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delight'])[1]/preceding::a[1]</value>
      <webElementGuid>1dda5fe2-cb38-451f-b67f-f89b60eeac0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>4324ddd1-2d01-490c-8b63-ecbc9cf7c7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/a</value>
      <webElementGuid>95a2771b-7193-4630-bbb8-a94b239d9085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = '211' and @id = 'show_more_211' and @href = '#' and (text() = '
                                        Cones
                                        
                                            3' or . = '
                                        Cones
                                        
                                            3')]</value>
      <webElementGuid>5d8693aa-9a62-4d7a-9aa3-663c6d5185cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
