<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to Cart</name>
   <tag></tag>
   <elementGuidId>620c9da9-b201-4f94-8f4a-4263b32a7f3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#224558</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='224558']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0103a73-ec20-4402-a025-9be20fcd60aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addToCart(this)</value>
      <webElementGuid>7f0e630a-80d3-4417-b3a9-cfbe5514d9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isfromcarousel</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0fcec87b-ea02-45c1-8585-2fdb1073ad2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>224558</value>
      <webElementGuid>7590e9e0-79b2-4b3b-9a07-69e44fdd0985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sample product</value>
      <webElementGuid>05854fc3-7af5-4124-bb52-48b5004551de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-category addtocartbtn</value>
      <webElementGuid>1189c07b-55dd-406e-95f2-eeae77c4116b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8306cca8-99fa-493d-8dc5-57fe64997324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-baseweight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9022fd7f-dc19-4372-ab34-a1ef4e83d0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-issoldbyweight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0c9705da-ddaf-4a6d-8d08-3bd37d9a7862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isshopsupportinyourlocationcart</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cc846e05-3f5f-44f5-9d0f-e62f92c10d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-starttime</name>
      <type>Main</type>
      <value>11:00</value>
      <webElementGuid>0c0b239b-5d28-46e2-8de4-7ee0dc1bb326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-endtime</name>
      <type>Main</type>
      <value>23:00</value>
      <webElementGuid>38b07571-4c8b-4850-8117-9f96d1040d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ispromoavail</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d81b6b8-b87d-4734-971b-8ec0415a5118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isprtdeliveryavailable</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>18fced8b-fffe-4957-9eb2-1874d81e1c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isprtdineinavailable</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>384f1266-32fc-4043-bc2a-a6b8d35a53c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isprtpickupavailable</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>71ec3c91-e0b8-4c76-957f-ee7b5204894a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isfrompromo</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>19028901-9513-4d84-8f80-a68fd7b7d343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saleprice</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>915ae9ee-a150-4e12-b8ac-3bf32bbcecd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orgprice</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c63f5b98-aa21-44cb-b62c-76431d1f6f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vendorid</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>86b348ef-9f0d-4092-93c4-782ced5bc3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vendorname</name>
      <type>Main</type>
      <value>Baskin Robbins - Technomall</value>
      <webElementGuid>438b6a6d-6811-486c-9626-8f97d4dcd763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>224558</value>
      <webElementGuid>ce6feda4-924b-43bc-843e-e28b5231c48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productname</name>
      <type>Main</type>
      <value>Sample product</value>
      <webElementGuid>1f216da9-5e66-43cf-95d8-973e06783de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c29d5f5c-1587-4132-95dd-26c7b18ae715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qty</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>298da2ea-bd4d-4269-a6fe-69c1b06b4af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>0f6b6ddf-8e4d-4265-857f-71f48a6c8411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>d13361aa-83fd-48f2-b54f-7197e60ff57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;224558&quot;)</value>
      <webElementGuid>47a0333a-4b42-409e-9fdd-9a4d6a8354c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='224558']</value>
      <webElementGuid>7a92d7d0-fbb2-4f03-be40-2a9b4df5bb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='products_container_1']/li/div/div[2]/button</value>
      <webElementGuid>02e431f6-5616-45a4-9602-b640c2be51b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹100.00'])[1]/following::button[1]</value>
      <webElementGuid>973e8fc9-755f-4094-a99b-7f249b2187fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample product'])[1]/following::button[1]</value>
      <webElementGuid>c58f1f49-43bf-491e-ab1e-e22c10ebe254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Hoppon'])[1]/preceding::button[1]</value>
      <webElementGuid>8298fa16-0067-4ac4-9c56-278ea930acc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/preceding::button[1]</value>
      <webElementGuid>bf0a5b36-e5ac-492f-8e67-47660ff9f109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to Cart']/parent::*</value>
      <webElementGuid>21fa3a1c-1e50-4550-9668-a9de8c9e2bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]/button</value>
      <webElementGuid>d5f50a6c-dac1-4c0c-b1a6-d3908cdaabaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '224558' and @name = 'Sample product' and @title = 'Add to Cart' and (text() = 'Add to Cart' or . = 'Add to Cart')]</value>
      <webElementGuid>4e03e4eb-3ed8-4184-a173-5b81898619b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
