<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_TYPE YOUR ORDER_prodt_gtaglink</name>
   <tag></tag>
   <elementGuidId>b288b50f-3e05-4ece-9242-40ab53bdb142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.prodt_gtaglink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='products_container_198']/li/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>51c6a060-e73d-48a8-acc2-10bfb036c2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prodt_gtaglink</value>
      <webElementGuid>e1b7db16-6d54-4c07-841d-4f8c31f5dfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hoppons3.s3.amazonaws.com/HoppOnImages/ProductImage/Prod/13/136364160582068975294cbd2.jpg</value>
      <webElementGuid>57c8acc3-6781-4d02-869f-dfe56aeb266e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Raspberry Toppings</value>
      <webElementGuid>9ab18f3b-f5ec-49c0-a668-859863034860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products_container_198&quot;)/li[@class=&quot;l-productlist__item&quot;]/div[@class=&quot;product_item&quot;]/a[1]/img[@class=&quot;prodt_gtaglink&quot;]</value>
      <webElementGuid>c95bb8c4-0cab-4f1e-85bd-fdc02b7da9d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='products_container_198']/li/div/a/img</value>
      <webElementGuid>3e463191-df99-4255-b9f8-4b8030c1886e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Raspberry Toppings']</value>
      <webElementGuid>480bde4e-b78d-4212-a2e9-8e231c9e54d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a/img</value>
      <webElementGuid>728d804f-183f-48f2-b6e3-be9d8e5f725c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hoppons3.s3.amazonaws.com/HoppOnImages/ProductImage/Prod/13/136364160582068975294cbd2.jpg' and @alt = 'Raspberry Toppings']</value>
      <webElementGuid>6425777f-aafb-4ebb-bd69-cf565e2ffa48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
