<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_28.00_prodt_gtaglink</name>
   <tag></tag>
   <elementGuidId>e233372e-57d1-4ae9-b6aa-5139039367f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='products_container_198']/li[3]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>983730ff-c297-4e2b-a7f6-97da81c9befa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prodt_gtaglink</value>
      <webElementGuid>65d7c3ef-d6c5-46c5-b1e5-5466b4303815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hoppons3.s3.amazonaws.com/HoppOnImages/ProductImage/Prod/13/1363641605783675625095c4d.jpg</value>
      <webElementGuid>4f304fc1-dc87-4b1d-aa3b-3c20d12977a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mango Toppings</value>
      <webElementGuid>88962605-1f1e-4528-a16a-0f21a76cdae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products_container_198&quot;)/li[@class=&quot;l-productlist__item&quot;]/div[@class=&quot;product_item&quot;]/a[1]/img[@class=&quot;prodt_gtaglink&quot;]</value>
      <webElementGuid>b63bc9ab-1d5d-4b16-94e9-a42968f2eebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='products_container_198']/li[3]/div/a/img</value>
      <webElementGuid>525abf44-d6c4-464e-a67c-04c21166b242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mango Toppings']</value>
      <webElementGuid>4c3d098f-288b-44ff-a0c5-8ca6a7eb23e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a/img</value>
      <webElementGuid>5cc0fef7-eb2f-4f44-beef-c64d2bdbb0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hoppons3.s3.amazonaws.com/HoppOnImages/ProductImage/Prod/13/1363641605783675625095c4d.jpg' and @alt = 'Mango Toppings']</value>
      <webElementGuid>d7e51b7a-89fc-4c43-86e7-959a7092c5a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
