<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use</name>
   <tag></tag>
   <elementGuidId>b9fa8e7a-575f-4d88-a422-166a81c493b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>use</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>https://shoptest.hopponapp.com/wp-content/themes/Hoppon/assets/img/icons.svg#heart</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products_container_1865&quot;)/li[@class=&quot;l-productlist__item&quot;]/div[@class=&quot;product_item&quot;]/div[@class=&quot;robocart displayaddtocart&quot;]/a[@class=&quot;l-icon&quot;]/i[@class=&quot;l-wishlist&quot;]/svg[1]/use[1]</value>
   </webElementProperties>
</WebElementEntity>
