<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_6 Item(s)</name>
   <tag></tag>
   <elementGuidId>98db5736-c093-4573-8d4d-d9c520d2e263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header__item_cartpage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='header__item_cartpage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>08284794-a14a-46c8-b1d8-56982bfef702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__item-name</value>
      <webElementGuid>a5982c9a-31de-4913-ab01-3dbf77d30fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header__item_cartpage</value>
      <webElementGuid>cb36ffa9-d1d0-4143-a9ca-83b0bed81299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6 Item(s)</value>
      <webElementGuid>6f61bbaa-ab7f-4aec-87f1-e3906019bc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header__item_cartpage&quot;)</value>
      <webElementGuid>d57cf85f-62f5-41b8-b77e-23f45d545e2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='header__item_cartpage']</value>
      <webElementGuid>a680989c-e14b-452b-aa19-7c00a5aec16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='loggedincart']/a/span/span</value>
      <webElementGuid>feb41c31-3473-4aef-8345-78aceb02f551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to earn Hoppon Cash?'])[1]/following::span[3]</value>
      <webElementGuid>a7bf9a0d-a113-488c-99e7-aa6689435e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='in cart'])[1]/preceding::span[1]</value>
      <webElementGuid>2d3439e9-2fd2-4b42-9d68-47cf00e14c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUICK ORDER'])[1]/preceding::span[2]</value>
      <webElementGuid>4f1e197d-45a1-4e0d-810a-d411d81c221c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6 Item(s)']/parent::*</value>
      <webElementGuid>d052d613-ed77-4ee5-8f00-5b52cd155471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a/span/span</value>
      <webElementGuid>1aa45f24-ef05-47f5-b50e-c72b118eaee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'header__item_cartpage' and (text() = '6 Item(s)' or . = '6 Item(s)')]</value>
      <webElementGuid>003c0a20-1634-4ec6-a3f8-f71420be2ead</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
