<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No</name>
   <tag></tag>
   <elementGuidId>d8fabb47-71a0-4428-a7d0-e6780c034afa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pickupcartproceedconfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pickupcartproceedconfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e957920-5440-48a7-9736-08367aa20a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91ec2aaa-9d1a-41a3-8832-71e0dfc16996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-category prdtcartremove</value>
      <webElementGuid>57f4a3b7-b00e-4d9b-8b54-e27f22b9ec74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e3c3826-4d54-49ea-951b-cd5c829d71d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>removeprdt</value>
      <webElementGuid>95efa85b-b08a-4090-97d8-08f792a5d0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pickupcartproceedconfirm</value>
      <webElementGuid>8b9723e0-352a-42bb-958a-6d0badfbe9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>07b57fe4-30a3-4270-948a-13128d251154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pickupcartproceedconfirm&quot;)</value>
      <webElementGuid>645de4bf-4610-4c70-a2bc-01644be2b6d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pickupcartproceedconfirm']</value>
      <webElementGuid>65cbac96-a60e-48c3-ac20-69fdd1811aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pickupcartproceedmsg']/div/div/div[2]/button</value>
      <webElementGuid>fe28c7a6-b156-4fd0-95ea-34eb77a77522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[9]/following::button[1]</value>
      <webElementGuid>716d4648-bbc1-43de-9abf-6ebef9c2275a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[8]/following::button[2]</value>
      <webElementGuid>11869c07-b8dd-4e5f-98eb-a4bb875e97a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[10]/preceding::button[2]</value>
      <webElementGuid>5c851d11-6eb2-4901-bb0c-87c3460db6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[11]/preceding::button[4]</value>
      <webElementGuid>fbf19daa-6f00-4a09-9f60-4cc55b48f31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div[2]/button</value>
      <webElementGuid>ac7fa3d9-5bf0-4d0c-b2a4-4370f85a7487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'removeprdt' and @id = 'pickupcartproceedconfirm' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>78dbdbfd-51cf-4fc6-866f-4e2936cdc1f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
