<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Order Summary</name>
   <tag></tag>
   <elementGuidId>09d23532-c8e3-455f-86bb-198a53f0ebd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pickup_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pickup_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8988f11b-0bb0-4337-b2dc-3395cc8e956e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bbe3a70d-e259-446e-a0ee-9bbb53eb5e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn  btn-category ordersummaryhover ordersummarybtnclass</value>
      <webElementGuid>a3980d2b-b0dd-4c7f-a15f-1ec67aa8107c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery_btn</value>
      <webElementGuid>e142b8ec-8800-440b-8965-d20947828bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pickup_btn</value>
      <webElementGuid>e3273cad-4116-4940-af59-e320adf9de1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order Summary</value>
      <webElementGuid>900e19e7-85e4-4e40-a500-c96e95f27672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pickup_btn&quot;)</value>
      <webElementGuid>437f808e-ae3e-4b16-b548-09b90acdfa12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pickup_btn']</value>
      <webElementGuid>502106cf-8ae1-425e-9581-290a73c4cc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pickup']/form/div/div/button</value>
      <webElementGuid>7153bbe4-6e32-4818-9fce-21f3e5d7c6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Phone Number:'])[1]/following::button[1]</value>
      <webElementGuid>9374b6de-a34c-4a16-b9a7-cd3afa02eb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Customer Name:'])[1]/following::button[1]</value>
      <webElementGuid>a3935d7d-dd94-44e2-a6aa-4365a7a70f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Address:'])[1]/preceding::button[1]</value>
      <webElementGuid>821fc51b-72cd-46c9-b66c-25a244c8f7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aneesh'])[2]/preceding::button[1]</value>
      <webElementGuid>066f7b70-3125-4211-a438-7fa7e25b948f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Order Summary']/parent::*</value>
      <webElementGuid>862af226-4bfa-4157-9fa8-d384612519f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/button</value>
      <webElementGuid>ebefa261-3505-4881-8d10-b344604050d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'delivery_btn' and @id = 'pickup_btn' and (text() = 'Order Summary' or . = 'Order Summary')]</value>
      <webElementGuid>74f5ffed-c4bb-48ba-948c-9fde191dcc2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
