<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proceed to payment</name>
   <tag></tag>
   <elementGuidId>5e3bd214-cb87-4024-951d-76af91d06261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onlinepaymentproceed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='onlinepaymentproceed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49296770-149d-4896-98ad-5f4eb51f8dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42846869-bcf7-40f1-9465-573c0d1102b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onlinepaymentproceed</value>
      <webElementGuid>41ad17ef-dcaf-440a-a069-94899c496c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_btn</value>
      <webElementGuid>8dcc26b0-f9dd-41e2-91e3-3a1fd91b20e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn  btn-category placeanordercls</value>
      <webElementGuid>8e497b73-3d2c-4263-b311-b31f0a7801c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.keyCode == myorderFunction();</value>
      <webElementGuid>5ce20775-3ab5-47d2-b237-ea8acd489f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed to payment</value>
      <webElementGuid>a58b54a0-0bf9-47a5-a58a-b46acb469662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onlinepaymentproceed&quot;)</value>
      <webElementGuid>9c017842-c1f6-4f83-b149-6cab5eae253b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='onlinepaymentproceed']</value>
      <webElementGuid>0272f70e-1a94-4f63-b02d-3bea24f3e53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='summary']/div[5]/button</value>
      <webElementGuid>8ad758de-a32a-41e0-aed6-a2ba35d76bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONFIRM ORDER'])[1]/following::button[1]</value>
      <webElementGuid>5dbd7b89-ce88-4337-b566-816b8c139063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon supports UPI payment.'])[1]/following::button[2]</value>
      <webElementGuid>bd0d00ed-13dc-451c-bd13-733d90d48549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The below item(s) cannot be ordered by the selected Dispatch Type:'])[1]/preceding::button[1]</value>
      <webElementGuid>b4de5482-1210-4c92-a86c-325b78eda0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GOOD KNIGHT PATCHES BABY SAFE'])[3]/preceding::button[1]</value>
      <webElementGuid>b8d723be-183c-4ec0-87d1-b05043694b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed to payment']/parent::*</value>
      <webElementGuid>f1a1fdb9-7c8c-42f9-b191-728dbc76e2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>54da5b80-0bcb-4ea7-bef9-36e1a7d3af17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'onlinepaymentproceed' and @name = 'order_btn' and (text() = 'Proceed to payment' or . = 'Proceed to payment')]</value>
      <webElementGuid>0b22b9b6-23f2-45ae-9c9d-1d3d5e86d58f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
