<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CartItemExpand</name>
   <tag></tag>
   <elementGuidId>3b1857fe-f9fc-4842-94eb-231fa158dfe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='plus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38700080-63aa-4d75-9977-ffc36fcf0640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cssCircle plusSign</value>
      <webElementGuid>47a96f10-18af-42df-869d-18b00509f7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plus</value>
      <webElementGuid>16603c54-a82e-4a93-a3de-a312d4c2ff9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show Cart item(s)</value>
      <webElementGuid>492dc7a2-0400-42f5-a41a-922fae3417a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>17f6b2d0-81e1-4e2b-9d2f-06105006eac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plus&quot;)</value>
      <webElementGuid>7da668d2-a265-4ca8-895a-6ed397b9d3c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='plus']</value>
      <webElementGuid>6876e00f-b341-4b37-be96-cceaa7014e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h4[@id='mart5span']/span/span</value>
      <webElementGuid>59f8a915-e521-40db-8908-b67c882e60b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart: Preethy Supermarket'])[1]/following::span[2]</value>
      <webElementGuid>f85fe943-eb3a-492b-9cd6-13d6e8f62c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to show the item(s) in Cart.'])[1]/preceding::span[1]</value>
      <webElementGuid>853532dc-cbc9-4dd5-9e59-7d11a10db47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item(s)'])[1]/preceding::span[3]</value>
      <webElementGuid>ceec2796-9337-476f-a993-18cfe4d257ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      <webElementGuid>acadc887-43d2-45de-b75f-8dc34e148e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4[2]/span/span</value>
      <webElementGuid>2ac066ce-02f2-47c1-8732-1a92614e7baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'plus' and @title = 'Show Cart item(s)' and (text() = '+' or . = '+')]</value>
      <webElementGuid>31affb48-ccf6-4d56-be2f-542343289c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
