<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConformationAlert</name>
   <tag></tag>
   <elementGuidId>0e48ad90-41fd-4463-bc55-b2a2f0c800d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hopponmessageid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='hopponmessageid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>54fcef0d-ac53-4bdb-a7bd-8e532d9a8521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hopponmessageid</value>
      <webElementGuid>04129f33-7499-4f60-9580-956fea2452ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The estimated pickup time of your order is  2 hour(s). 1. Hoppon may allow pickup of order(s) by another person, if the Hoppon Account holder has provided in writing from the registered account e-mail an authority to release goods to this person. 2. Any person(s) picking up an order on behalf of a Hoppon account holder must present their photo-ID in store and allow Hoppon to take a copy of this ID for fraud prevention purposes.</value>
      <webElementGuid>b18ebb70-ba58-4e4e-829e-f1c35a3e35da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hopponmessageid&quot;)</value>
      <webElementGuid>b03a6afd-841c-480c-ad6b-4b6888c59fd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='hopponmessageid']</value>
      <webElementGuid>51bba167-b6bd-4d68-9121-10ff4a12dd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hopponmessages']/div/div/div[2]/p</value>
      <webElementGuid>d7279671-f7cf-4644-8502-bb1afc8672f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[19]/following::p[1]</value>
      <webElementGuid>a8e06b5a-6bb0-4c3e-8ae6-1933c7034499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[18]/following::p[2]</value>
      <webElementGuid>cc605b03-ba01-477c-9ae3-687e5867a14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[20]/preceding::p[1]</value>
      <webElementGuid>ef01ef25-c5db-4eb6-ba5e-813c0ca2bb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[21]/preceding::p[2]</value>
      <webElementGuid>0318d14d-a59d-479f-ab6b-52bb46b60f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[44]/div/div/div[2]/p</value>
      <webElementGuid>8902822d-5f08-4862-8bfc-416f7b29342b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'hopponmessageid' and (text() = 'The estimated pickup time of your order is  2 hour(s). 1. Hoppon may allow pickup of order(s) by another person, if the Hoppon Account holder has provided in writing from the registered account e-mail an authority to release goods to this person. 2. Any person(s) picking up an order on behalf of a Hoppon account holder must present their photo-ID in store and allow Hoppon to take a copy of this ID for fraud prevention purposes.' or . = 'The estimated pickup time of your order is  2 hour(s). 1. Hoppon may allow pickup of order(s) by another person, if the Hoppon Account holder has provided in writing from the registered account e-mail an authority to release goods to this person. 2. Any person(s) picking up an order on behalf of a Hoppon account holder must present their photo-ID in store and allow Hoppon to take a copy of this ID for fraud prevention purposes.')]</value>
      <webElementGuid>0f4977fb-1c6e-4cdf-9f01-4aaef7e8253c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
