<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DispatchTypeExp</name>
   <tag></tag>
   <elementGuidId>6879daa5-b488-4a51-a9c5-f94752af00c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#plustab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='plustab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9abcefe2-2b9e-487d-aec3-1b2b96ec433c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cssCircle minusSign</value>
      <webElementGuid>feec30b3-ef74-42b1-abdc-9c0488025469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plustab</value>
      <webElementGuid>d684425d-bb5d-400d-9dec-fbaa74e4fbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hide Dispatch Type(s)</value>
      <webElementGuid>ad20bede-e90f-4b0a-9a46-fb96c9e305c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>–</value>
      <webElementGuid>3276045d-5447-4ddd-bd85-5b9abb19a95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plustab&quot;)</value>
      <webElementGuid>e6f16052-35d0-43d3-b581-34a78d1d1354</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='plustab']</value>
      <webElementGuid>ce2c5966-ca3d-4192-aaeb-0d85bfbe9e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='appendl']/span/span</value>
      <webElementGuid>54803ea7-1dc2-4e27-9f39-237ea619a8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dispatch Type: Preethy Supermarket'])[1]/following::span[2]</value>
      <webElementGuid>f2c14cce-599e-41ba-85fa-e09b28314101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹ 668.90'])[1]/following::span[2]</value>
      <webElementGuid>db41091b-4910-468b-aaa3-e1f10062b430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to hide the Dispatch Type(s).'])[1]/preceding::span[1]</value>
      <webElementGuid>61dcf458-41dd-4e49-a746-ce998a5d0978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick Up'])[1]/preceding::span[2]</value>
      <webElementGuid>878f7b1a-ae8a-4603-870d-47faa919a407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='–']/parent::*</value>
      <webElementGuid>41f8d799-0432-4190-a124-0235a564b458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span/span</value>
      <webElementGuid>8e9ae8ff-7061-4244-aff0-f44c8d5f74a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'plustab' and @title = 'Hide Dispatch Type(s)' and (text() = '–' or . = '–')]</value>
      <webElementGuid>79ebc06b-de6b-4b41-95cc-035f5fc40797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
