<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HopponCashAvailable</name>
   <tag></tag>
   <elementGuidId>b8489985-f689-4518-864f-62aa622b6baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#availhopponcashbycus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='availhopponcashbycus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>59e7d179-401b-45cf-bf8c-abb6ccd33b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>1ee12aa4-9578-42c0-8869-8b1b8cf127e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>availhopponcashbycus</value>
      <webElementGuid>39cb500a-6838-456c-abf2-720f2af1d266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce2464b3-72b6-47f6-921d-b62574102738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availhopponcashbycus&quot;)</value>
      <webElementGuid>46e9ef85-054e-4d28-a4ff-dc68c20d2ff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='availhopponcashbycus']</value>
      <webElementGuid>3498d3e1-2ae3-4ea6-bd84-2075d0668b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cash_refresh']/tbody/tr[2]/td[2]</value>
      <webElementGuid>58166014-3144-4c52-a9c1-1ff28473307e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Hoppon Cash :'])[2]/following::td[1]</value>
      <webElementGuid>830e4a21-d74f-476f-8e69-be3336f49876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use My Hoppon Cash :'])[1]/following::td[3]</value>
      <webElementGuid>3f1972a3-2abb-4cf3-96df-5ce854da7ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Hoppon Cash Amount :'])[1]/preceding::td[1]</value>
      <webElementGuid>878c7d4a-0f22-43c2-8424-e6e952259597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Options:'])[1]/preceding::td[3]</value>
      <webElementGuid>2a9de963-4be9-4414-874c-a8fbde87f057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>081d5ff3-76b5-4a6f-b91e-2cdbb1cd1fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td[2]</value>
      <webElementGuid>84a448ee-5672-40dc-bf18-bba2df2cbccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'availhopponcashbycus' and (text() = '0' or . = '0')]</value>
      <webElementGuid>c09a4af2-270c-4e37-94a6-83c52183acf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
