<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Customer Name_customer name</name>
   <tag></tag>
   <elementGuidId>514297c3-12c3-40ff-9b7d-9a21914bcd80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_delivery_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_delivery_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93a2b06f-3c79-4ac8-8a93-8b729f44c5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d21ebd0-1d3b-40e4-894b-08d91818184e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>fffb5bfd-4298-4321-8952-e7859e9166c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2ffff134-efd2-44e0-ae37-57ef35405cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_delivery_name</value>
      <webElementGuid>b431bca8-a41e-4b10-abf7-16b1b9e7efa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Customer Name</value>
      <webElementGuid>1c74993f-49f3-45dc-8558-123316baa50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer name</value>
      <webElementGuid>b1fc2e99-73a5-4858-9a24-dc5e1cbef148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aneesh</value>
      <webElementGuid>7e779104-ef52-4b9e-a2e3-cfa3cf9b27f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_delivery_name&quot;)</value>
      <webElementGuid>469b4caf-3248-4eeb-9dca-019e9143ec82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_delivery_name']</value>
      <webElementGuid>491de305-fb4e-4a01-936d-1e8cf324bba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='namefon']/input</value>
      <webElementGuid>a33c46b0-bcd2-4bd7-8a79-2a31a63663dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>0a871c45-39f4-4ed4-aa66-5bcf1709e2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'order_delivery_name' and @placeholder = 'Enter Customer Name' and @name = 'customer name']</value>
      <webElementGuid>c9a59907-2894-4a30-8f0f-b334d7d193fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
