<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_669.72_promocode</name>
   <tag></tag>
   <elementGuidId>bbe55824-b22b-450e-9094-5d06024157df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#promocode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='promocode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dce72b1f-519f-4555-ad6d-77eb61d458a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fce5f8a5-a101-4935-87b8-b0f4ea0cbc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>promocode</value>
      <webElementGuid>b8424c1f-1a83-4f68-812d-03a70f03d64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promocode</value>
      <webElementGuid>b656a631-0230-4557-a56e-ef47a8635900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter promo code</value>
      <webElementGuid>9470d4ac-5740-4437-9b2c-c98af480c6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promocode&quot;)</value>
      <webElementGuid>9edd5501-6c9d-4560-b4bd-b1c9ba83078f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='promocode']</value>
      <webElementGuid>9c6fcf90-7087-4851-823f-8154bd3cacf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='summary']/div[3]/input</value>
      <webElementGuid>6b8b0b03-06df-4d49-9d0f-f6fab94b2256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/form/div[3]/input</value>
      <webElementGuid>defb00f9-63ab-49b1-985f-7f58cd74cb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'promocode' and @id = 'promocode' and @placeholder = 'Enter promo code']</value>
      <webElementGuid>bb90a1c8-15fc-4a4b-aa90-95263d7e22b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
