<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Online Payment_paymentmode</name>
   <tag></tag>
   <elementGuidId>febe4a8c-1556-4595-95b3-92f14d0db77d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onlinemode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='onlinemode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>060ebc2b-1fe1-4f23-a062-b27a28b767a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a85abb52-df4e-4068-b5e0-986b08cb8a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onlinemode</value>
      <webElementGuid>4af3cab2-6018-4321-bdae-14190ed95659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentmode</value>
      <webElementGuid>7d126c03-9763-4d4f-b704-f8a5be33dfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>online</value>
      <webElementGuid>9fb58809-b9ba-4d59-b8fb-e8cb55bff52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onlinemode&quot;)</value>
      <webElementGuid>1153201d-bcbe-4764-b0a9-5a747a26cf5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='onlinemode']</value>
      <webElementGuid>2f2df722-799f-4d45-894e-549901d4158e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='onlinetd']/input</value>
      <webElementGuid>2ec7e1e7-6cda-47fe-b161-b49a7fdbd6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>146b1d53-dbb9-410b-b88f-6ec635539461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'onlinemode' and @name = 'paymentmode']</value>
      <webElementGuid>df497547-9245-4d7f-9759-8e1e5435c0c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
