<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cash on Delivery_paymentmode</name>
   <tag></tag>
   <elementGuidId>32fea165-6855-436f-a18c-389ee4bf8d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codmode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codmode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc020330-ebad-4475-9465-30aa676f6feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>05d10d11-b892-45a7-9eeb-b1f095eac19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codmode</value>
      <webElementGuid>7e5424f1-652c-451d-91bb-4d9dcf688b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentmode</value>
      <webElementGuid>52e4f10e-1742-45cb-a949-a2ed85ba5a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>cod</value>
      <webElementGuid>52a68ba6-ab2d-4842-a06e-329b3ae2de30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codmode&quot;)</value>
      <webElementGuid>2b4b884c-cf38-4161-b969-c8bd6ce6bb3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codmode']</value>
      <webElementGuid>da187dc0-7b64-4aee-b0a8-d532d9e64253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='codtd']/input</value>
      <webElementGuid>078e7cd3-d8ef-4580-a779-293b1e503d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td[2]/input</value>
      <webElementGuid>5090514a-3521-46c9-9c33-9cd50228e552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'codmode' and @name = 'paymentmode']</value>
      <webElementGuid>2d60ba8f-368c-47be-a5c9-b8ca74335345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
