<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Phone Number_order_delivery_phone</name>
   <tag></tag>
   <elementGuidId>e48f3957-4648-49eb-aa28-2c5073509319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_delivery_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_delivery_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>735ae7cf-d6a7-4310-9cdc-fce737aa19a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>660eca59-011c-4ce1-8870-7e7ad5889eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return AllowOnlyNumbers(event);</value>
      <webElementGuid>e97cdf08-85e6-4c8e-a78c-26f838eca071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>96d9e1c8-16c3-4d21-8456-adf6523c174e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_delivery_phone</value>
      <webElementGuid>c0e125a4-0a50-45d6-ac3e-28339acee294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone number</value>
      <webElementGuid>276d2532-edc0-4b27-a240-6b71479274bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_delivery_phone</value>
      <webElementGuid>cf3fdd60-680b-4768-9680-60bc03adf8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>7012899846</value>
      <webElementGuid>463aa015-343a-46c1-8ebb-67aff88be1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_delivery_phone&quot;)</value>
      <webElementGuid>17ba89f0-c867-4f31-9d88-66c88b468fa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_delivery_phone']</value>
      <webElementGuid>ab37a036-8af2-4407-8e21-1d787b804419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='namefon']/input[3]</value>
      <webElementGuid>715f9002-9fc4-41ac-ae15-c9cf2a0edeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input[3]</value>
      <webElementGuid>28d4e65c-db14-413c-a56c-c2533b039b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'order_delivery_phone' and @placeholder = 'Phone number' and @name = 'order_delivery_phone']</value>
      <webElementGuid>c3caa64e-57b1-487f-b76c-944c4d2ab8bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
