<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>POfferMessage</name>
   <tag></tag>
   <elementGuidId>381ad152-1f29-4366-a573-2c2bef4808ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.genericmodalmsg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pickupcartproceedmsg']/div/div/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>78feee03-cb26-4b42-b694-baa21d13d001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>genericmodalmsg</value>
      <webElementGuid>a0388977-c781-48af-821a-c9f99c8e7b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adding additional items worth ₹1379.10 will get you 15%  off on this order. And the promotional item: Chicken fry 250 gm. Do you want to ADD MORE items to cart?</value>
      <webElementGuid>69b5e31b-1cda-421a-8d31-60e50e6a8e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pickupcartproceedmsg&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content modalheight&quot;]/div[@class=&quot;modal-body&quot;]/p[@class=&quot;genericmodalmsg&quot;]</value>
      <webElementGuid>d68b4030-8528-46db-821a-446541146011</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pickupcartproceedmsg']/div/div/div[2]/p</value>
      <webElementGuid>1bf94585-9285-4839-8e41-ad75db256884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[9]/following::p[1]</value>
      <webElementGuid>5e5667c7-b3b6-4d00-b030-c165c4e68fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[8]/following::p[2]</value>
      <webElementGuid>e769a5ae-6c42-44e9-97a8-c2454e3350e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[10]/preceding::p[1]</value>
      <webElementGuid>428df95a-4bef-4157-b0fd-ea5338fd8c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoppon'])[11]/preceding::p[2]</value>
      <webElementGuid>7c232d50-71c9-4d1d-a4ff-3d169ed74359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div[2]/p</value>
      <webElementGuid>495b154a-a24b-4186-8a76-1a78a39976d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Adding additional items worth ₹1379.10 will get you 15%  off on this order. And the promotional item: Chicken fry 250 gm. Do you want to ADD MORE items to cart?' or . = 'Adding additional items worth ₹1379.10 will get you 15%  off on this order. And the promotional item: Chicken fry 250 gm. Do you want to ADD MORE items to cart?')]</value>
      <webElementGuid>2a8eb1c7-8cbb-4ed3-b31e-5cd5b3664caa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
