<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_6</name>
   <tag></tag>
   <elementGuidId>fc399ceb-91cf-4e23-86cf-d4e890757f8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemqtytotal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='itemqtytotal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5badd414-8dfb-4bd0-9fea-e1d8735e9165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemqtytotal</value>
      <webElementGuid>54065c1c-bcec-439b-8583-b962f945f047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quant</value>
      <webElementGuid>005a7d78-7bbc-4db2-8397-b7a1fb5e2c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>859e8782-8ac7-4b1f-abde-a9980970fd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemqtytotal&quot;)</value>
      <webElementGuid>533347cc-1c65-46e0-9fe6-76d3983d5ba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='itemqtytotal']</value>
      <webElementGuid>9b08bba3-a04c-41bd-9880-1696124cb228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/div/label/span</value>
      <webElementGuid>20834743-3f43-4897-84e1-2169f658eb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Price: ₹48.00'])[1]/following::span[3]</value>
      <webElementGuid>4a3f1c9c-6e19-4532-99d4-f411bd6f4a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹ 668.90'])[1]/preceding::span[1]</value>
      <webElementGuid>fe82e0fb-35fb-4df7-8e82-56b569e3c295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6']/parent::*</value>
      <webElementGuid>20e95cb8-236b-4974-aba3-96d79dc451e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>eee6a8b6-7f4e-4e8b-91c0-5736f21b30e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'itemqtytotal' and (text() = '6' or . = '6')]</value>
      <webElementGuid>fa7a4d63-dd97-4734-8480-43aaf285807c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
