<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_6</name>
   <tag></tag>
   <elementGuidId>58884d57-1e63-4cbc-8d11-bf8c0882ccbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#no_of_items</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='no_of_items']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>34f906ca-1eef-4d51-afc2-f8a3fc524a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_of_items</value>
      <webElementGuid>0eb2f96c-616b-401d-8c01-460f6cd1a6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>8d8fb1cf-ff7e-450e-85cb-8240633a5b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_of_items&quot;)</value>
      <webElementGuid>081e4466-8059-499e-900a-5b58bc759b67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='no_of_items']</value>
      <webElementGuid>cf3a9021-9536-438a-a7e6-1ddec9a5e254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='summary']/table/tbody/tr/td[2]</value>
      <webElementGuid>037845be-2474-4e21-9eba-1d19922b2d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of item(s) :'])[1]/following::td[1]</value>
      <webElementGuid>61f51e77-b598-404e-87fa-088b0cd50531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary: Preethy Supermarket'])[1]/following::td[2]</value>
      <webElementGuid>e1f0ee97-e8b3-4507-8aef-f1c7c8b98f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Total :'])[1]/preceding::td[1]</value>
      <webElementGuid>580e7847-7bd7-4324-8ebc-93024b797fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹ 668.90'])[2]/preceding::td[2]</value>
      <webElementGuid>af18c54a-02b7-4e95-b45d-aacf657af323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td[2]</value>
      <webElementGuid>67a1baa5-bc7b-44c2-80dc-ae2772b33637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'no_of_items' and (text() = '6' or . = '6')]</value>
      <webElementGuid>64e095db-a14a-4522-ab10-4b5ebe5bd3b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
