<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_669.72_specialinstruction</name>
   <tag></tag>
   <elementGuidId>f5c08263-1bec-448d-9fd9-b38e8804b895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#specialinstruction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='specialinstruction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>655842a2-3036-4a9b-bb0b-4c2ebbad37b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>textarea3</value>
      <webElementGuid>344e70a4-5d1a-4f45-bc67-9e0411415ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>265ce8b3-571b-4773-b158-e67f47587417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>specialinstruction</value>
      <webElementGuid>35cc652e-2fb5-4e40-a95a-58ca4322730f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>specialinstruction</value>
      <webElementGuid>166106ac-b38b-4650-b7f0-a9c70c8a58fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add a Note (extra napkins, extra sauce...)</value>
      <webElementGuid>0795fc65-e6cc-451b-a36d-66a58a9477ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;specialinstruction&quot;)</value>
      <webElementGuid>2d1c1492-6d38-4f35-add2-bac7b83effd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='specialinstruction']</value>
      <webElementGuid>7cbeb93c-95f9-41ed-8886-250fcceb0e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='specialinstruction_div']/textarea</value>
      <webElementGuid>68b11d07-245c-4281-ae61-9a9fbd0633fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2ea98cc7-2c41-4eb5-b9f6-d5ccc33ce64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'specialinstruction' and @id = 'specialinstruction' and @placeholder = 'Add a Note (extra napkins, extra sauce...)']</value>
      <webElementGuid>741000a3-0d71-4cba-93c1-f2f44775128a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
